services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    container_name: bookcove-fastapi-container
    environment:
      - REDIS_HOST=redis  
      - RABBITMQ_HOST=rabbitmq
      - BASE_URL=${BASE_URL}
      - BOOK_API=${BOOK_API}
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: bookcove-redis-container 

  rabbitmq:
    image: rabbitmq:3-management-alpine 
    ports:
      - "5672:5672"   
      - "15672:15672" 
    container_name: bookcove-rabbitmq-container

  consumer:
    build: . 
    command: ["python", "receiver.py"]
    depends_on:
      - redis
      - rabbitmq
    container_name: bookcove-consumer-container
    environment:
      - REDIS_HOST=redis        
      - RABBITMQ_HOST=rabbitmq   
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 